MVC_ASP_Test/Controllers/RoleController.cs
using Company.Database.Access;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_ASP_Test.Models;

namespace MVC_ASP_Test.Controllers
{
    // authorize for admin and Super Admin
    [Authorize(Roles = "Admin, Super Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this._roleManager = roleManager;
            this._userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            if (ModelState.IsValid)
            {
                if ((await _roleManager.CreateAsync(role)).Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in (await _roleManager.CreateAsync(role)).Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                    return View(role);
                }
            }
            else
            {
                foreach (var error in (await _roleManager.CreateAsync(role)).Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View(role);
            }
        }
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                return View(role);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string id, IdentityRole Role)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
            }
            else
            {
                role.Name = Role.Name;
                role.NormalizedName = Role.Name.ToUpper();
                await this._roleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View(Role);
        }
        public async Task<IActionResult> AddOrRemoveUser(string id)
        {
            var role = await this._roleManager.FindByIdAsync(id);

            var users = await this._userManager.Users.ToListAsync();

            var usersInRole = new List<UserRoleViewModel>();

            foreach (var user in users)
            {
                var userRole = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };
                if (await this._userManager.IsInRoleAsync(user, role.Name))
                {
                    userRole.IsSelected = true;
                }
                else
                {
                    userRole.IsSelected = false;
                }
                usersInRole.Add(userRole);
            }
            ViewBag.RoleId = role.Id;
            return View(usersInRole);
        }
        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUser(string id, IEnumerable<UserRoleViewModel> users)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);
                    if (appUser != null)
                    {
                        if (user.IsSelected && !(await _userManager.IsInRoleAsync(appUser, id)))
                        {
                            await _userManager.AddToRoleAsync(appUser, role.Name);
                        }
                        else
                        {
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);
                        }
                    }
                }
            }
            return RedirectToAction(nameof(Edit), new { id = role.Id });
        }
    }
}

MVC_ASP_Test/Controllers/UserController.cs
using Company.Database.Access;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MVC_ASP_Test.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UserController(UserManager<ApplicationUser> userManager)
        {
            this._userManager = userManager;
        }

        // GET: UserController
        public async Task<IActionResult> Index(string searchInp)
        {
            List<ApplicationUser> users;
            if (string.IsNullOrEmpty(searchInp))
            {
                users = await _userManager.Users.ToListAsync();
            }
            else
            {
                users = await _userManager.Users.Where(user => user.FirstName.ToLower().Contains(searchInp.Trim().ToLower())
                || user.LastName.ToLower().Contains(searchInp.Trim().ToLower())).ToListAsync();
            }
            return View(users);
        }

        // GET: UserController/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var users = await this._userManager.FindByIdAsync(id.ToString());
            return View();
        }

        // GET: UserController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var user = await this._userManager.FindByIdAsync(id.ToString());
            return View(user);
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, IFormCollection collection, ApplicationUser user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var firstName = collection["FirstName"];
                    var lastName = collection["LastName"];
                    var Email = collection["Email"];
                    var userName = collection["Email"].ToString().Split('@')[0]; // UserName
                    var normalizedEmail = collection["Email"].ToString().ToUpper();
                    var passwordHash = this._userManager.PasswordHasher.HashPassword(user, user.PasswordHash.ToString());
                    var normailizedUserName = collection["Email"].ToString().ToUpper().Split('@')[0];
                    await this._userManager.UpdateAsync(new ApplicationUser
                    {
                        Id = id.ToString(),
                        FirstName = firstName,
                        LastName = lastName,
                        Email = Email,
                        UserName = userName,
                        NormalizedEmail = normalizedEmail,
                        NormalizedUserName = normailizedUserName
                    });
                    return RedirectToAction(nameof(Index));
                }

            }
            catch
            {
                return View();
            }
            return View();
        }

        // POST: UserController/Delete/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id, IFormCollection collection)
        {
            try
            {
                var user = await this._userManager.FindByIdAsync(id.ToString());
                await this._userManager.DeleteAsync(user);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC_ASP_Test/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_ASP_Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_ASP_Test.styles.css" asp-append-version="true" />
    @* custom style *@
    @RenderSection("css", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_ASP_Test</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Home" && ViewContext.RouteData.Values["action"].ToString() == "Index" ? "text-success" : "text-dark")" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Account" && ViewContext.RouteData.Values["action"].ToString() == "SignUp" ? "text-success" : "text-dark")" asp-area="" asp-controller="Account" asp-action="SignUp">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Account" && ViewContext.RouteData.Values["action"].ToString() == "SignIn" ? "text-success" : "text-dark")" asp-area="" asp-controller="Account" asp-action="SignIn">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC_ASP_Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC_ASP_Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_ASP_Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_ASP_Test.styles.css" asp-append-version="true" />
    @* custom style *@
    @RenderSection("css", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_ASP_Test</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Home" && ViewContext.RouteData.Values["action"].ToString() == "Index" ? "text-success" : "text-dark")" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">

                            <a class="nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "About" && ViewContext.RouteData.Values["action"].ToString() == "Index" ? "text-success" : "text-dark")" asp-area="" asp-controller="About" asp-action="Index">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Orders" && ViewContext.RouteData.Values["action"].ToString() == "Index" ? "text-success" : "text-dark")" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                         <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        @* check if user is logged in and is admin or not to display the signout *@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="SignUp">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="SignIn">Login</a>
                            </li>
                        }
                        
                        @* <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Account" && ViewContext.RouteData.Values["action"].ToString() == "SignUp" ? "text-success" : "text-dark")" asp-area="" asp-controller="Account" asp-action="SignUp">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Account" && ViewContext.RouteData.Values["action"].ToString() == "SignIn" ? "text-success" : "text-dark")" asp-area="" asp-controller="Account" asp-action="SignIn">Login</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC_ASP_Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC_ASP_Test/Views/Shared/_TableActionButtons.cshtml
<td>
    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model.OrderId">Edit</a>
</td>
<td>
    <a asp-action="Cust_Orders" class="btn btn-info" asp-route-id="@Model.CustomerId">List user orders</a>
</td>
<td>
    <a asp-action="Order_Details" class="btn btn-primary" asp-route-id="@Model.OrderId">Details</a>
</td>
<td>
    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model.OrderId">Delete</a>
</td>